filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /usr/share/filebeat/logs/live_firefox.log
    scan_frequency: 1s
    tail_files: true       # start reading new lines from the end
    fields:
      source: firefox_build
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

logging:
  level: info
  to_files: true
  files:
    path: /usr/share/filebeat/logs
    name: filebeat
    keepfiles: 7
